version: '3'

services:
  db: 
    image: mongo:6.0
    container_name: db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
 
  
